@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant ":AddCommand" as AddCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

box Storage STORAGE_COLOR_T1
participant "s:Storage" as Storage STORAGE_COLOR
end box

[-> LogicManager : execute"add n/John e/john@gmail.com s/A1234567D p/99998888"
activate LogicManager

LogicManager -> AddressBookParser : parseCommand"add n/John e/john@gmail.com s/A1234567D p/99998888"
activate AddressBookParser

create AddCommandParser
AddressBookParser -> AddCommandParser
activate AddCommandParser

AddCommandParser --> AddressBookParser
deactivate AddCommandParser

AddressBookParser -> AddCommandParser : parse("n/John e/john@gmail.com s/A1234567D p/99998888")
activate AddCommandParser

create AddCommand
AddCommandParser -> AddCommand
activate AddCommand


AddCommand --> AddCommand :
deactivate AddCommand

AddCommand --> AddressBookParser
deactivate AddCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddCommand -[hidden]-> AddressBookParser
destroy AddCommand

AddressBookParser --> LogicManager
deactivate AddressBookParser

LogicManager -> AddCommand : execute(m)
activate AddCommand


AddCommand -> Model : setPerson(person)
activate Model

Model -> Storage : saveAddressBook()
activate Storage

Storage --> Model
deactivate Storage

Model --> AddCommand
deactivate Model

AddCommand -> Model : updateFilteredPersonList(...)
activate Model

Model --> AddCommand
deactivate Model

deactivate Model

create CommandResult
AddCommand -> CommandResult
activate CommandResult

CommandResult --> AddCommand
deactivate CommandResult

AddCommand --> LogicManager : r
deactivate AddCommand

[<--LogicManager
deactivate LogicManager
@enduml
